test:
  adapter: postgresql
  encoding: unicode
  database: beacon_email_service_test
  pool: 2
  username: tbierwirth

development:
  adapter: postgresql
  encoding: unicode
  database: beacon_email_service_development
  pool: 2
  username: tbierwirth

production:
  adapter: postgresql
  encoding: unicode
  database: beacon_email_service_production
  pool: 5
  port: <%= ENV['PORT'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_URL'] %>
