test:
  adapter: postgresql
  encoding: unicode
  database: beacon_email_service_test
  pool: 2
  username: tbierwirth

development:
  adapter: postgresql
  encoding: unicode
  database: beacon_email_service_development
  pool: 2
  username: tbierwirth

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
